#site_name: Руководство по выживанию для бекера
site_name: potyk-io
dev_addr: 127.0.0.1:8001

theme:
  favicon: assets/favicon-16x16.png
  logo: assets/favicon-32x32.png
  name: material
  palette:
    primary: blue

  features:
    # Якори
    - navigation.tracking
    # Табы
    - navigation.tabs
    - navigation.tabs.sticky
    # В левой навигации все раскрыто
    - navigation.expand
    # Кнопка "Вверх"
    - navigation.top
    # Секции в рамках одного раздела
    - navigation.sections
    # Поиск
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang:
        - en
        - ru
  - awesome-pages

nav:
  - index.md
  - ... | Python/**/*.md
  - ... | Ops/**/*.md
  - ... | Frontend/**/*.md

markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - attr_list


extra:
  analytics:
    provider: google
    property: UA-190154899-1
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/potykion
      name: тг
    - icon: fontawesome/brands/github
      link: https://github.com/potykion
      name: гх
    - icon: material/mirror
      link: https://potykion.github.io/
      name: зеркало
